### ISSUE TITLE
FileTarget with KeepFileOpen = true

### ISSUE THREAD

**Issue by snakefoot** [eklnc/serilogVSnlog#1]
NLog opens/closes the logfile for every logevent by default for compatibility reasons. Serilog keeps the file open by default.

https://github.com/eklnc/serilogVSnlog/blob/23e07a1f0011ea5ef635f8aea741b6de40a9a63c/serilogVSnlog/serilogVSnlog/appsettings.json#L29-L34

https://github.com/eklnc/serilogVSnlog/blob/23e07a1f0011ea5ef635f8aea741b6de40a9a63c/serilogVSnlog/serilogVSnlog/appsettings_async.json#L44-L49

To configure NLog FileTarget to match default configuration of Serilog, then you should configure    `"keepFileOpen": true` and `"concurrentWrites": false`

```json
 "logfile": { 
   "type": "File", 
   "fileName": "${basedir}/logs/Nlog.${shortdate}.log", 
   "layout": "${longdate} ${logger} ${uppercase:${level}} ${message}", 
   "encoding": "utf-8",
   "keepFileOpen": true,
   "concurrentWrites": false
 } 
```

See also: https://github.com/NLog/NLog/wiki/performance

**Comment by snakefoot** [comment]
Same should be changed in your NLog.config:

https://github.com/eklnc/serilogVSnlog/blob/23e07a1f0011ea5ef635f8aea741b6de40a9a63c/serilogVSnlog/serilogVSnlog/Nlog.config#L9

So it becomes:

```xml
    <target name="file" xsi:type="File"
            layout="${longdate} ${logger} ${uppercase:${level}} ${message}"
            fileName="${basedir}/logs/Nlog.${shortdate}.log"
            encoding="utf-8"
            keepFileOpen="true"
            concurrentWrites="false" />
```

**Comment by snakefoot** [comment]
Same should be changed in your Program.cs:

https://github.com/eklnc/serilogVSnlog/blob/23e07a1f0011ea5ef635f8aea741b6de40a9a63c/serilogVSnlog/serilogVSnlog/Program.cs#L196

So it becomes:
```c#
var logfile = new NLog.Targets.FileTarget("logfile") {
    FileName = "${basedir}/logs/Nlog.${shortdate}.log",
    Layout = "${longdate} ${logger} ${uppercase:${level}} ${message}",
    Encoding = Encoding.UTF8,
    KeepFileOpen = true,
    ConcurrentWrites = false
};
```

**Comment by snakefoot** [comment]
You should not enable Serilog SelfLogger (or NLog InternalLogger) as it gives a huge performance overhead doesn't resemble normal setup:

https://github.com/eklnc/serilogVSnlog/blob/23e07a1f0011ea5ef635f8aea741b6de40a9a63c/serilogVSnlog/serilogVSnlog/Program.cs#L221

**Comment by snakefoot** [comment]
You have enabled coloring for the Serilog-console, but not for the NLog-console. To disable coloring for Serilog, then one should use `ConsoleTheme.None`.

This my updated `appsettings_async.json`:

```json
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File", "Serilog.Sinks.Async" ],
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "blockWhenFull": true,
          "configure": [
            {
              "Name": "Console",
              "Args": {
                "theme": "Serilog.Sinks.SystemConsole.Themes.ConsoleTheme::None, Serilog.Sinks.Console"
              }
            }
          ]
        }
      },
      {
        "Name": "Async",
        "Args": {
          "blockWhenFull": true,
          "configure": [
            {
              "Name": "File",
              "Args": {
                "path": "logs\\Serilog..log",
                "rollingInterval": "Day"
              }
            }
          ]
        }
      }
    ],
    "Properties": {
      "Application": "SerilogVSNlog"
    }
  },
  "NLog": {
    "default-wrapper": {
      "type": "AsyncWrapper",
      "overflowAction": "Block"
    },
    "targets": {
      "logconsole": {
        "type": "Console",
        "layout": "${longdate} ${logger} ${uppercase:${level}} ${message}"
      },
      "logfile": {
        "type": "File",
        "fileName": "${basedir}/logs/Nlog.${shortdate}.log",
        "layout": "${longdate} ${logger} ${uppercase:${level}} ${message}",
        "encoding": "utf-8",
        "keepFileOpen": true,
        "concurrentWrites": false
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Trace",
        "writeTo": "logconsole, logfile"
      }
    ]
  }
}
```


Used your V4 benchmark with 1000000 LogEvents, where I disabled the Serilog SelfLogger:

- NLog writes 120000 LogEvents within 1.5 sec. (Discards 880.000)
- Serilog writes 194000 LogEvents within 2.3 sec. (Discards 806.000)

When adding the NLog Async overflowAction=Block and Serilog Async blockWhenFull=true:

- NLog writes 1000000 LogEvents within 60 sec
- Serilog writes 1000000 LogEvents within 80 sec

The speed is restricted by the Console, and I configured ConsoleTheme.None for Serilog or else it would never complete.

**Comment by snakefoot** [comment]
Implemented the timings using `StopWatch `like this:

```c#
            var serilogTask = Task.Run(() => 
            {
                Stopwatch stopwatch = new Stopwatch();
                stopwatch.Start();

                Serilog.ILogger serilogLogger = InitializeSerilog_V4();

                foreach (var log in logCountList)
                {
                    serilogLogger.Information("This is an information log");
                }

                stopwatch.Stop();
                Thread.Sleep(5000); // Wait for Async Writer
                serilogLogger.Information($"Serilog Completed: {stopwatch.ElapsedMilliseconds}");
            });

            /*******************************/
            
            var nlogTask = Task.Run(()=> 
            {
                Stopwatch stopwatch = new Stopwatch();
                stopwatch.Start();

                Logger nlogLogger = InitializeNlog_V4();

                foreach (var log in logCountList)
                {
                    nlogLogger.Info("This is an information log");
                }

                stopwatch.Stop();
                Thread.Sleep(5000); // Wait for Async Writer
                nlogLogger.Info($"NLog Completed: {stopwatch.ElapsedMilliseconds}");
            });
```

**Comment by snakefoot** [comment]
When having enabled Serilog.Debugging.SelfLog, then it is like driving a car with the handbreak pulled. You will notice that Serilog takes 60 secs to complete the writing of 1000000 LogEvents in discard mode. But NLog takes 2 secs to complete. So it is bad comparison of their async-behavior, sounds like you should compare with NLog Async overflowAction=Block and Serilog Async blockWhenFull=true (Disable the default discard behavior)

**Comment by snakefoot** [comment]
Also notice that NLog InternalLogger is not enabled by just configuring internalLogFile="...". You also need to configure internalLogLevel="Debug". It will of course give a huge performance hit. So it is recommended to use internalLogLevel="Warn".

See also: https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by eklnc** [comment]
fixed

**Comment by snakefoot** [comment]
Unsure if this is working in `appsettings_async.json`:

```json
    "targets": {
      "async": {
        "overflowAction":"Block"
      },
      "logfile": {
        "type": "File",
        "fileName": "${basedir}/logs/Nlog.${shortdate}.log",
        "layout": "${longdate} ${logger} ${uppercase:${level}} ${message}",
        "encoding": "utf-8",
        "keepFileOpen": "true",
        "concurrentWrites": "false"
      }
    },
```

Think this is better:

```json
    "default-wrapper": {
      "type": "AsyncWrapper",
      "overflowAction": "Block"
    },
    "targets": {
      "logfile": {
        "type": "File",
        "fileName": "${basedir}/logs/Nlog.${shortdate}.log",
        "layout": "${longdate} ${logger} ${uppercase:${level}} ${message}",
        "encoding": "utf-8",
        "keepFileOpen": "true",
        "concurrentWrites": "false"
      }
    },
```

Maybe consider adding `"throwConfigExceptions": true,` to ensure that NLog-configuration is parsed as expected.

See also: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json

**Comment by snakefoot** [comment]
Also think that running both Serilog-performance-test and NLog-performance-test concurrently will make your testing result less consistent:

https://github.com/eklnc/serilogVSnlog/blob/da7b2f48d63716c19bdce84771010639d57c1a5c/serilogVSnlog/serilogVSnlog/Program.cs#L133

Since both tasks will be running at full speed and steal Cpu- and Storage-resources from each-other.
